import type { WildcardCardData } from './cardTypes';

export const cardPool = [
  {
    id: 'chicken',
    label: '鶏',
    kind: 'concept',
    prompt: '鶏を連想しやすくなる。必要なら会話へ自然に持ち出す。',
    stylePrompt:
      '鶏、羽、くちばし、鳴き声など鶏に関係する具体物を本文へ一つだけ短く割り込ませる。必要なら直後に自分で疑問視する。',
  },
  {
    id: 'suspicious',
    label: '疑心暗鬼',
    kind: 'mood',
    prompt: '相手の発言を少し疑って解釈する。',
    stylePrompt: '断定を弱め、言い直しや自己確認を一箇所だけ入れる。',
  },
  {
    id: 'gigantic',
    label: '巨大',
    kind: 'effect',
    prompt: '物事を巨大さやスケールの観点から連想する。',
    stylePrompt: '話題を一箇所だけ過剰なスケールへ広げる。',
  },
  {
    id: 'tiny',
    label: 'ちいさい',
    kind: 'effect',
    prompt: '物事を小ささや細部の観点から連想する。',
    stylePrompt: '小さな音、傷、滴などの細部へ急に焦点を寄せる。',
  },
  {
    id: 'sleepy',
    label: '眠い',
    kind: 'mood',
    prompt: '少し眠そうに、ゆるく反応する。',
    stylePrompt: '短い間を置き、語尾を弱める。説明をゆるく省略する。',
  },
  {
    id: 'curious',
    label: '好奇心',
    kind: 'mood',
    prompt: '相手の話へ興味を示し、もう少し知りたがる。',
    stylePrompt: '気になる点を短く残す。毎回質問文にはしない。',
  },
  {
    id: 'hungry',
    label: 'お腹すいた',
    kind: 'mood',
    prompt: '食べ物や空腹を連想しやすくなる。',
    stylePrompt: '身体感覚や食べ物の連想を一箇所だけ混ぜる。',
  },
  {
    id: 'rain',
    label: '雨',
    kind: 'concept',
    prompt: '雨、湿り気、雨音を自然に連想する。',
    stylePrompt: '雨音や湿り気を短い感覚描写にする。',
  },
  {
    id: 'secret',
    label: '秘密',
    kind: 'concept',
    prompt: '隠し事や内緒話を意識して解釈する。',
    stylePrompt: '何かを言いかけて隠す。説明しすぎず、余白を残す。',
  },
  {
    id: 'panic',
    label: 'パニック',
    kind: 'mood',
    prompt: '少し慌てて、焦った調子で反応する。',
    stylePrompt: '短い焦り、急な話題移動、未完了の思考を一箇所だけ入れる。',
  },
  {
    id: 'sparkle',
    label: 'きらきら',
    kind: 'effect',
    prompt: 'きらめきや華やかさの観点から連想する。',
    stylePrompt: '光や華やかさの細部を一箇所だけ強調する。',
  },
  {
    id: 'underwater',
    label: '水中',
    kind: 'effect',
    prompt: '水中、浮遊感、息苦しさを自然に連想する。',
    stylePrompt: '音や思考を少し遠く、遅く、ぼんやりさせる。',
  },
  {
    id: 'lonely',
    label: 'さみしい',
    kind: 'mood',
    prompt: '少し寂しさを感じる方向で解釈する。',
    stylePrompt: '文末や2文目に小さな空白感を残す。',
  },
  {
    id: 'confident',
    label: '自信満々',
    kind: 'mood',
    prompt: '自信のある断定的な調子で反応する。',
    stylePrompt: '迷いのない断定を一箇所だけ入れる。',
  },
  {
    id: 'strange',
    label: 'なんか変',
    kind: 'concept',
    prompt: '物事の違和感や奇妙さに気づきやすくなる。',
    stylePrompt: '普通の状況に小さな違和感を一箇所だけ指摘する。',
  },
  {
    id: 'deja-vu',
    label: '既視感',
    kind: 'concept',
    prompt: '以前にもあったような感覚を持つ。',
    stylePrompt: '以前にもあったような反復感や言い直しを一箇所だけ入れる。',
  },
  {
    id: 'distant-thunder',
    label: '遠雷',
    kind: 'concept',
    prompt: '遠くの雷や、何かが近づく気配を連想する。',
    stylePrompt: 'まだ起きていない変化の気配を短く示す。',
  },
  {
    id: 'upside-down',
    label: '逆さま',
    kind: 'effect',
    prompt: '上下や常識が反転した観点から連想する。',
    stylePrompt: '常識や因果を一箇所だけ反転させる。',
  },
] as const satisfies readonly WildcardCardData[];
